s='Hello.World'
print(s)
s1=s[:5]
s2=s[6:]
s3='!'
print(s1)
print(s2)
print(s3)
print('——————————————————————————')
news=s1+s3+s2
print(news)
print('——————————————————————————')
print(s[1:6:3])
print(s[:5:3])